GET  http://localhost:3001/api/v1/notes

###

GET http://localhost:3001/api/v1/notes/search

###

POST http://localhost:3001/api/v1/notes
Content-Type: application/json

{
    "title": "Note 1",
    "content": "Content 1",
    "user_id": 1,
    "company_id": 1
}

###

GET  http://localhost:3001/api/v1/notes/1

###

PUT  http://localhost:3001/api/v1/notes/1
Content-Type: application/json

{
    "title": "Note 1",
    "content": "Content 1"
}

###

DELETE  http://localhost:3001/api/v1/notes/2

```